// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AccountCenterInitParameters struct {

	// JSON object with the managed API fields; omitted fields remain unmanaged.
	Configuration *string `json:"configuration,omitempty" tf:"configuration,omitempty"`
}

type AccountCenterObservation struct {

	// JSON object with the managed API fields; omitted fields remain unmanaged.
	Configuration *string `json:"configuration,omitempty" tf:"configuration,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AccountCenterParameters struct {

	// JSON object with the managed API fields; omitted fields remain unmanaged.
	// +kubebuilder:validation:Optional
	Configuration *string `json:"configuration,omitempty" tf:"configuration,omitempty"`
}

// AccountCenterSpec defines the desired state of AccountCenter
type AccountCenterSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AccountCenterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountCenterInitParameters `json:"initProvider,omitempty"`
}

// AccountCenterStatus defines the observed state of AccountCenter.
type AccountCenterStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AccountCenterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountCenter is the Schema for the AccountCenters API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,logto}
type AccountCenter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configuration) || (has(self.initProvider) && has(self.initProvider.configuration))",message="spec.forProvider.configuration is a required parameter"
	Spec   AccountCenterSpec   `json:"spec"`
	Status AccountCenterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountCenterList contains a list of AccountCenters
type AccountCenterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountCenter `json:"items"`
}

// Repository type metadata.
var (
	AccountCenter_Kind             = "AccountCenter"
	AccountCenter_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountCenter_Kind}.String()
	AccountCenter_KindAPIVersion   = AccountCenter_Kind + "." + CRDGroupVersion.String()
	AccountCenter_GroupVersionKind = CRDGroupVersion.WithKind(AccountCenter_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountCenter{}, &AccountCenterList{})
}
