// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type IDTokenConfigurationInitParameters struct {

	// JSON object with the managed API fields; omitted fields remain unmanaged.
	Configuration *string `json:"configuration,omitempty" tf:"configuration,omitempty"`
}

type IDTokenConfigurationObservation struct {

	// JSON object with the managed API fields; omitted fields remain unmanaged.
	Configuration *string `json:"configuration,omitempty" tf:"configuration,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type IDTokenConfigurationParameters struct {

	// JSON object with the managed API fields; omitted fields remain unmanaged.
	// +kubebuilder:validation:Optional
	Configuration *string `json:"configuration,omitempty" tf:"configuration,omitempty"`
}

// IDTokenConfigurationSpec defines the desired state of IDTokenConfiguration
type IDTokenConfigurationSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   IDTokenConfigurationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IDTokenConfigurationInitParameters `json:"initProvider,omitempty"`
}

// IDTokenConfigurationStatus defines the observed state of IDTokenConfiguration.
type IDTokenConfigurationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               IDTokenConfigurationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IDTokenConfiguration is the Schema for the IDTokenConfigurations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,logto}
type IDTokenConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configuration) || (has(self.initProvider) && has(self.initProvider.configuration))",message="spec.forProvider.configuration is a required parameter"
	Spec   IDTokenConfigurationSpec   `json:"spec"`
	Status IDTokenConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IDTokenConfigurationList contains a list of IDTokenConfigurations
type IDTokenConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IDTokenConfiguration `json:"items"`
}

// Repository type metadata.
var (
	IDTokenConfiguration_Kind             = "IDTokenConfiguration"
	IDTokenConfiguration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IDTokenConfiguration_Kind}.String()
	IDTokenConfiguration_KindAPIVersion   = IDTokenConfiguration_Kind + "." + CRDGroupVersion.String()
	IDTokenConfiguration_GroupVersionKind = CRDGroupVersion.WithKind(IDTokenConfiguration_Kind)
)

func init() {
	SchemeBuilder.Register(&IDTokenConfiguration{}, &IDTokenConfigurationList{})
}
