apiVersion: user.logto.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/user
  labels:
    testing.upbound.io/example-name: user
  name: user
  namespace: crossplane-system
spec:
  forProvider:
    name: user_name
    primaryEmail: user_primary_email@example.fr
    profile:
      familyName: family name
      givenName: given name
      middleName: middle name
      nickname: nickname
    roleIdsRefs:
    - name: role

---

apiVersion: role.logto.m.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/user
  labels:
    testing.upbound.io/example-name: role
  name: role
  namespace: crossplane-system
spec:
  forProvider:
    description: role_description
    name: role_name
    type: User
