// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ResourceInitParameters struct {

	// (Number) The access token TTL in seconds. It affects the exp claim of the access token granted for this resource.
	// The access token TTL in seconds. It affects the `exp` claim of the access token granted for this resource.
	AccessTokenTTL *float64 `json:"accessTokenTtl,omitempty" tf:"access_token_ttl,omitempty"`

	// (String) The unique resource indicator. Should be a valid URI.
	// The unique resource indicator. Should be a valid URI.
	Indicator *string `json:"indicator,omitempty" tf:"indicator,omitempty"`

	// (String) The name of the resource.
	// The name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ResourceObservation struct {

	// (Number) The access token TTL in seconds. It affects the exp claim of the access token granted for this resource.
	// The access token TTL in seconds. It affects the `exp` claim of the access token granted for this resource.
	AccessTokenTTL *float64 `json:"accessTokenTtl,omitempty" tf:"access_token_ttl,omitempty"`

	// (String) The unique identifier of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The unique resource indicator. Should be a valid URI.
	// The unique resource indicator. Should be a valid URI.
	Indicator *string `json:"indicator,omitempty" tf:"indicator,omitempty"`

	// (Boolean)
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// (String) The name of the resource.
	// The name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) (see below for nested schema)
	Scopes []ScopesObservation `json:"scopes,omitempty" tf:"scopes,omitempty"`
}

type ResourceParameters struct {

	// (Number) The access token TTL in seconds. It affects the exp claim of the access token granted for this resource.
	// The access token TTL in seconds. It affects the `exp` claim of the access token granted for this resource.
	// +kubebuilder:validation:Optional
	AccessTokenTTL *float64 `json:"accessTokenTtl,omitempty" tf:"access_token_ttl,omitempty"`

	// (String) The unique resource indicator. Should be a valid URI.
	// The unique resource indicator. Should be a valid URI.
	// +kubebuilder:validation:Optional
	Indicator *string `json:"indicator,omitempty" tf:"indicator,omitempty"`

	// (String) The name of the resource.
	// The name of the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ScopesInitParameters struct {
}

type ScopesObservation struct {

	// (Number)
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The unique identifier of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// (String)
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type ScopesParameters struct {
}

// ResourceSpec defines the desired state of Resource
type ResourceSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ResourceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ResourceInitParameters `json:"initProvider,omitempty"`
}

// ResourceStatus defines the observed state of Resource.
type ResourceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ResourceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Resource is the Schema for the Resources API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,logto}
type Resource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.indicator) || (has(self.initProvider) && has(self.initProvider.indicator))",message="spec.forProvider.indicator is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ResourceSpec   `json:"spec"`
	Status ResourceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ResourceList contains a list of Resources
type ResourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Resource `json:"items"`
}

// Repository type metadata.
var (
	Resource_Kind             = "Resource"
	Resource_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Resource_Kind}.String()
	Resource_KindAPIVersion   = Resource_Kind + "." + CRDGroupVersion.String()
	Resource_GroupVersionKind = CRDGroupVersion.WithKind(Resource_Kind)
)

func init() {
	SchemeBuilder.Register(&Resource{}, &ResourceList{})
}
