// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/the-ccsn/provider-upjet-logto/apis/namespaced/role/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this User.
func (mg *User) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.RoleIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.RoleIdsRefs,
		Selector:      mg.Spec.ForProvider.RoleIdsSelector,
		To: reference.To{
			List:    &v1alpha1.RoleList{},
			Managed: &v1alpha1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RoleIds")
	}
	mg.Spec.ForProvider.RoleIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.RoleIdsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.RoleIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.RoleIdsRefs,
		Selector:      mg.Spec.InitProvider.RoleIdsSelector,
		To: reference.To{
			List:    &v1alpha1.RoleList{},
			Managed: &v1alpha1.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RoleIds")
	}
	mg.Spec.InitProvider.RoleIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.RoleIdsRefs = mrsp.ResolvedReferences

	return nil
}
