// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ProfileInitParameters struct {

	// (String)
	FamilyName *string `json:"familyName,omitempty" tf:"family_name,omitempty"`

	// (String)
	GivenName *string `json:"givenName,omitempty" tf:"given_name,omitempty"`

	// (String)
	MiddleName *string `json:"middleName,omitempty" tf:"middle_name,omitempty"`

	// (String)
	Nickname *string `json:"nickname,omitempty" tf:"nickname,omitempty"`
}

type ProfileObservation struct {

	// (String)
	FamilyName *string `json:"familyName,omitempty" tf:"family_name,omitempty"`

	// (String)
	GivenName *string `json:"givenName,omitempty" tf:"given_name,omitempty"`

	// (String)
	MiddleName *string `json:"middleName,omitempty" tf:"middle_name,omitempty"`

	// (String)
	Nickname *string `json:"nickname,omitempty" tf:"nickname,omitempty"`
}

type ProfileParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	FamilyName *string `json:"familyName,omitempty" tf:"family_name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	GivenName *string `json:"givenName,omitempty" tf:"given_name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	MiddleName *string `json:"middleName,omitempty" tf:"middle_name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Nickname *string `json:"nickname,omitempty" tf:"nickname,omitempty"`
}

type UserInitParameters struct {

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Primary email address for the user. It should be unique across all users.
	// Primary email address for the user. It should be unique across all users.
	PrimaryEmail *string `json:"primaryEmail,omitempty" tf:"primary_email,omitempty"`

	// (Attributes) (see below for nested schema)
	Profile *ProfileInitParameters `json:"profile,omitempty" tf:"profile,omitempty"`

	// (Set of String) An array of API resource role IDs to assign.
	// An array of API resource role IDs to assign.
	// +crossplane:generate:reference:type=github.com/the-ccsn/provider-upjet-logto/apis/namespaced/role/v1alpha1.Role
	// +listType=set
	// +kubebuilder:validation:Optional
	RoleIds []*string `json:"roleIds,omitzero" tf:"role_ids"`

	// References to Role in role to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsRefs []v2.NamespacedReference `json:"roleIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Role in role to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsSelector *v2.NamespacedSelector `json:"roleIdsSelector,omitempty" tf:"-"`

	// (String) Username for the user. It should be unique across all users.
	// Username for the user. It should be unique across all users.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Primary email address for the user. It should be unique across all users.
	// Primary email address for the user. It should be unique across all users.
	PrimaryEmail *string `json:"primaryEmail,omitempty" tf:"primary_email,omitempty"`

	// (Attributes) (see below for nested schema)
	Profile *ProfileObservation `json:"profile,omitempty" tf:"profile,omitempty"`

	// (Set of String) An array of API resource role IDs to assign.
	// An array of API resource role IDs to assign.
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`

	// (String) Username for the user. It should be unique across all users.
	// Username for the user. It should be unique across all users.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Primary email address for the user. It should be unique across all users.
	// Primary email address for the user. It should be unique across all users.
	// +kubebuilder:validation:Optional
	PrimaryEmail *string `json:"primaryEmail,omitempty" tf:"primary_email,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Profile *ProfileParameters `json:"profile,omitempty" tf:"profile,omitempty"`

	// (Set of String) An array of API resource role IDs to assign.
	// An array of API resource role IDs to assign.
	// +crossplane:generate:reference:type=github.com/the-ccsn/provider-upjet-logto/apis/namespaced/role/v1alpha1.Role
	// +kubebuilder:validation:Optional
	// +listType=set
	RoleIds []*string `json:"roleIds,omitzero" tf:"role_ids"`

	// References to Role in role to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsRefs []v2.NamespacedReference `json:"roleIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Role in role to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsSelector *v2.NamespacedSelector `json:"roleIdsSelector,omitempty" tf:"-"`

	// (String) Username for the user. It should be unique across all users.
	// Username for the user. It should be unique across all users.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,logto}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserSpec   `json:"spec"`
	Status            UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
