// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/the-ccsn/provider-upjet-logto/apis/namespaced/api/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Role.
func (mg *Role) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.ScopeIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.ScopeIdsRefs,
		Selector:      mg.Spec.ForProvider.ScopeIdsSelector,
		To: reference.To{
			List:    &v1alpha1.ScopeList{},
			Managed: &v1alpha1.Scope{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ScopeIds")
	}
	mg.Spec.ForProvider.ScopeIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.ScopeIdsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.ScopeIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.ScopeIdsRefs,
		Selector:      mg.Spec.InitProvider.ScopeIdsSelector,
		To: reference.To{
			List:    &v1alpha1.ScopeList{},
			Managed: &v1alpha1.Scope{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ScopeIds")
	}
	mg.Spec.InitProvider.ScopeIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.ScopeIdsRefs = mrsp.ResolvedReferences

	return nil
}
