apiVersion: application.logto.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: application/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: grafana
  name: grafana
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: grafana
    name: gitops
