// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ApplicationInitParameters struct {

	// (List of String)
	// +kubebuilder:validation:Optional
	CorsAllowedOrigins []*string `json:"corsAllowedOrigins,omitzero" tf:"cors_allowed_origins"`

	// JSON for additional metadata; callback URI and CORS lists are managed separately.
	CustomClientMetadataExtra *string `json:"customClientMetadataExtra,omitempty" tf:"custom_client_metadata_extra,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean)
	IsThirdParty *bool `json:"isThirdParty,omitempty" tf:"is_third_party,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON for additional metadata; callback URI and CORS lists are managed separately.
	OidcClientMetadataExtra *string `json:"oidcClientMetadataExtra,omitempty" tf:"oidc_client_metadata_extra,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	PostLogoutRedirectUris []*string `json:"postLogoutRedirectUris,omitzero" tf:"post_logout_redirect_uris"`

	// (List of String)
	// +kubebuilder:validation:Optional
	RedirectUris []*string `json:"redirectUris,omitzero" tf:"redirect_uris"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ApplicationObservation struct {

	// (List of String)
	CorsAllowedOrigins []*string `json:"corsAllowedOrigins,omitempty" tf:"cors_allowed_origins,omitempty"`

	// JSON for additional metadata; callback URI and CORS lists are managed separately.
	CustomClientMetadataExtra *string `json:"customClientMetadataExtra,omitempty" tf:"custom_client_metadata_extra,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The unique identifier of the application.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean)
	IsAdmin *bool `json:"isAdmin,omitempty" tf:"is_admin,omitempty"`

	// (Boolean)
	IsThirdParty *bool `json:"isThirdParty,omitempty" tf:"is_third_party,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON for additional metadata; callback URI and CORS lists are managed separately.
	OidcClientMetadataExtra *string `json:"oidcClientMetadataExtra,omitempty" tf:"oidc_client_metadata_extra,omitempty"`

	// (List of String)
	PostLogoutRedirectUris []*string `json:"postLogoutRedirectUris,omitempty" tf:"post_logout_redirect_uris,omitempty"`

	// (List of String)
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// (String)
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ApplicationParameters struct {

	// (List of String)
	// +kubebuilder:validation:Optional
	CorsAllowedOrigins []*string `json:"corsAllowedOrigins,omitzero" tf:"cors_allowed_origins"`

	// JSON for additional metadata; callback URI and CORS lists are managed separately.
	// +kubebuilder:validation:Optional
	CustomClientMetadataExtra *string `json:"customClientMetadataExtra,omitempty" tf:"custom_client_metadata_extra,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	IsThirdParty *bool `json:"isThirdParty,omitempty" tf:"is_third_party,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON for additional metadata; callback URI and CORS lists are managed separately.
	// +kubebuilder:validation:Optional
	OidcClientMetadataExtra *string `json:"oidcClientMetadataExtra,omitempty" tf:"oidc_client_metadata_extra,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	PostLogoutRedirectUris []*string `json:"postLogoutRedirectUris,omitzero" tf:"post_logout_redirect_uris"`

	// (List of String)
	// +kubebuilder:validation:Optional
	RedirectUris []*string `json:"redirectUris,omitzero" tf:"redirect_uris"`

	// (String)
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ApplicationSpec defines the desired state of Application
type ApplicationSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ApplicationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApplicationInitParameters `json:"initProvider,omitempty"`
}

// ApplicationStatus defines the observed state of Application.
type ApplicationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ApplicationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Application is the Schema for the Applications API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,logto}
type Application struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ApplicationSpec   `json:"spec"`
	Status ApplicationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApplicationList contains a list of Applications
type ApplicationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Application `json:"items"`
}

// Repository type metadata.
var (
	Application_Kind             = "Application"
	Application_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Application_Kind}.String()
	Application_KindAPIVersion   = Application_Kind + "." + CRDGroupVersion.String()
	Application_GroupVersionKind = CRDGroupVersion.WithKind(Application_Kind)
)

func init() {
	SchemeBuilder.Register(&Application{}, &ApplicationList{})
}
