// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RoleInitParameters struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean)
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// (String) The name of the role. It should be unique within the tenant.
	// The name of the role. It should be unique within the tenant.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) API resource scopes assigned to the role. An empty list revokes all scopes; omission leaves them unmanaged. Changes preserve the role ID and memberships.
	// API resource scopes assigned to the role. An empty list revokes all scopes; omission leaves them unmanaged.
	// +crossplane:generate:reference:type=github.com/the-ccsn/provider-upjet-logto/apis/cluster/api/v1alpha1.Scope
	// +kubebuilder:validation:Optional
	ScopeIds []*string `json:"scopeIds,omitzero" tf:"scope_ids"`

	// References to Scope in api to populate scopeIds.
	// +kubebuilder:validation:Optional
	ScopeIdsRefs []v2.Reference `json:"scopeIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Scope in api to populate scopeIds.
	// +kubebuilder:validation:Optional
	ScopeIdsSelector *v2.Selector `json:"scopeIdsSelector,omitempty" tf:"-"`

	// (String) The type of the role. It cannot be changed after creation.
	// The type of the role. It cannot be changed after creation.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RoleObservation struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The unique identifier of the role.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean)
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// (String) The name of the role. It should be unique within the tenant.
	// The name of the role. It should be unique within the tenant.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) API resource scopes assigned to the role. An empty list revokes all scopes; omission leaves them unmanaged. Changes preserve the role ID and memberships.
	// API resource scopes assigned to the role. An empty list revokes all scopes; omission leaves them unmanaged.
	ScopeIds []*string `json:"scopeIds,omitempty" tf:"scope_ids,omitempty"`

	// (String) The type of the role. It cannot be changed after creation.
	// The type of the role. It cannot be changed after creation.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RoleParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// (String) The name of the role. It should be unique within the tenant.
	// The name of the role. It should be unique within the tenant.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) API resource scopes assigned to the role. An empty list revokes all scopes; omission leaves them unmanaged. Changes preserve the role ID and memberships.
	// API resource scopes assigned to the role. An empty list revokes all scopes; omission leaves them unmanaged.
	// +crossplane:generate:reference:type=github.com/the-ccsn/provider-upjet-logto/apis/cluster/api/v1alpha1.Scope
	// +kubebuilder:validation:Optional
	ScopeIds []*string `json:"scopeIds,omitzero" tf:"scope_ids"`

	// References to Scope in api to populate scopeIds.
	// +kubebuilder:validation:Optional
	ScopeIdsRefs []v2.Reference `json:"scopeIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Scope in api to populate scopeIds.
	// +kubebuilder:validation:Optional
	ScopeIdsSelector *v2.Selector `json:"scopeIdsSelector,omitempty" tf:"-"`

	// (String) The type of the role. It cannot be changed after creation.
	// The type of the role. It cannot be changed after creation.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// RoleSpec defines the desired state of Role
type RoleSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoleInitParameters `json:"initProvider,omitempty"`
}

// RoleStatus defines the observed state of Role.
type RoleStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Role is the Schema for the Roles API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,logto}
type Role struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RoleSpec   `json:"spec"`
	Status RoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleList contains a list of Roles
type RoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Role `json:"items"`
}

// Repository type metadata.
var (
	Role_Kind             = "Role"
	Role_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Role_Kind}.String()
	Role_KindAPIVersion   = Role_Kind + "." + CRDGroupVersion.String()
	Role_GroupVersionKind = CRDGroupVersion.WithKind(Role_Kind)
)

func init() {
	SchemeBuilder.Register(&Role{}, &RoleList{})
}
